{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerthub.componentName" (dict "root" . "component" "redis-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alerthub.labels" . | nindent 4 }}
data:
  redis.conf: |
    # Redis configuration
    appendonly yes
    ignore-warnings ARM64-COW-BUG
{{- end }}