apiVersion: v1
kind: Service
metadata:
  name: {{ include "alerthub.componentName" (dict "root" . "component" "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alerthub.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      {{- if .Values.web.service.nodePort }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "alerthub.componentName" (dict "root" . "component" "web") }}
  sessionAffinity: None
  type: {{ .Values.web.service.type }}